In [103]:
from matplotlib import dates as mdate
from matplotlib import pyplot as plt
import matplotlib.animation as animation


import pandas as pd

from time import sleep

from IPython.display import clear_output

import numpy as np

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, train_test_split

import random

import joblib

import random
from sklearn.model_selection import train_test_split

import numpy as np

from sklearn.pipeline import make_pipeline

from sklearn.preprocessing import StandardScaler

from sklearn.svm import SVC

from sklearn.linear_model import LogisticRegression

from sklearn.ensemble import RandomForestClassifier


from sklearn.model_selection import cross_val_score

import pickle

In [104]:
from Preprocessing import *

In [105]:
X = np.array(catchcompletearr)
y = np.array(catchresultarr)

X2 = np.array(pullcompletearr)
y2 = np.array(pullresultarr)

X3 = np.array(recoverycompletearr)
y3 = np.array(recoveryresultarr)

# Classification Models

## RandomForestClassifier

### Catch

In [137]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=random.randint(0, 50))

clf1 = make_pipeline(StandardScaler(), RandomForestClassifier(n_estimators=100))

clf1.fit(X_train, y_train)

predict_y = clf1.predict(X_test)
predict_y
getResults(predict_y, y_test)

Precision: 0.5 
Recall: 1.0 
Accuracy: 0.7727272727272727 
Fscore: 0.6666666666666666


### Pull

In [134]:

X_train, X_test, y_train, y_test = train_test_split(X2, y2, test_size=0.33, random_state=random.randint(0, 50))

clf2 = make_pipeline(StandardScaler(), RandomForestClassifier(n_estimators=100))

clf2.fit(X_train, y_train)

predict_y = clf2.predict(X_test)

getResults(predict_y, y_test)

Precision: 1.0 
Recall: 0.875 
Accuracy: 0.9545454545454546 
Fscore: 0.9333333333333333


### Recovery

In [136]:

X_train, X_test, y_train, y_test = train_test_split(X3, y3, test_size=0.33, random_state=random.randint(0, 50))

clf3 = make_pipeline(StandardScaler(), RandomForestClassifier(n_estimators=100))

clf3.fit(X_train, y_train)

predict_y = clf3.predict(X_test)

getResults(predict_y, y_test)

Precision: 1.0 
Recall: 0.75 
Accuracy: 0.8636363636363636 
Fscore: 0.8571428571428571


## SVM (Classification)

### Catch

In [144]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=random.randint(0, 50))

clf1 = make_pipeline(StandardScaler(), SVC(gamma='auto'))

clf1.fit(X_train, y_train)

predict_y = clf1.predict(X_test)
predict_y
getResults(predict_y, y_test)

Precision: 0.4166666666666667 
Recall: 1.0 
Accuracy: 0.6818181818181818 
Fscore: 0.5882352941176471


### Pull

In [147]:
X_train, X_test, y_train, y_test = train_test_split(X2, y2, test_size=0.33, random_state=random.randint(0, 50))

clf2 = make_pipeline(StandardScaler(), SVC(gamma='auto'))

clf2.fit(X_train, y_train)

predict_y = clf2.predict(X_test)

getResults(predict_y, y_test)

Precision: 1.0 
Recall: 0.8461538461538461 
Accuracy: 0.9090909090909091 
Fscore: 0.9166666666666666


### Recovery

In [150]:
X_train, X_test, y_train, y_test = train_test_split(X3, y3, test_size=0.33, random_state=random.randint(0, 50))

clf3 = make_pipeline(StandardScaler(), SVC(gamma='auto'))

clf3.fit(X_train, y_train)

predict_y = clf3.predict(X_test)

getResults(predict_y, y_test)

Precision: 1.0 
Recall: 1.0 
Accuracy: 1.0 
Fscore: 1.0


## Logistic Regression 

### Catch 

In [154]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=random.randint(0, 50))

clf1 = make_pipeline(StandardScaler(), LogisticRegression(penalty='l2')) #penalty prevents overfitting

clf1.fit(X_train, y_train)

predict_y = clf1.predict(X_test)
predict_y
getResults(predict_y, y_test)

Precision: 1.0 
Recall: 0.9 
Accuracy: 0.9545454545454546 
Fscore: 0.9473684210526316


### Pull

In [165]:
X_train, X_test, y_train, y_test = train_test_split(X2, y2, test_size=0.33, random_state=random.randint(0, 50))

clf2 = make_pipeline(StandardScaler(), LogisticRegression(penalty='l2')) #penalty prevents overfitting

clf2.fit(X_train, y_train)

predict_y = clf2.predict(X_test)

getResults(predict_y, y_test)

Precision: 0.7142857142857143 
Recall: 1.0 
Accuracy: 0.9090909090909091 
Fscore: 0.8333333333333333


### Recovery

In [172]:
X_train, X_test, y_train, y_test = train_test_split(X3, y3, test_size=0.33, random_state=random.randint(0, 50))

clf3 = make_pipeline(StandardScaler(), LogisticRegression(penalty='l2')) #penalty prevents overfitting

clf3.fit(X_train, y_train)

predict_y = clf3.predict(X_test)

getResults(predict_y, y_test)

Precision: 0.8888888888888888 
Recall: 0.8888888888888888 
Accuracy: 0.9090909090909091 
Fscore: 0.8888888888888888


## XGB Classification

In [115]:
from xgboost import XGBClassifier

### Catch

In [189]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=random.randint(0, 50))

clf1 = make_pipeline(StandardScaler(), XGBClassifier(n_estimators=100)) 

clf1.fit(X_train, y_train)

predict_y = clf1.predict(X_test)
predict_y
getResults(predict_y, y_test)

Precision: 1.0 
Recall: 1.0 
Accuracy: 1.0 
Fscore: 1.0


### Pull

In [198]:
X_train, X_test, y_train, y_test = train_test_split(X2, y2, test_size=0.33, random_state=random.randint(0, 50))

clf2 = make_pipeline(StandardScaler(), XGBClassifier(n_estimators=100)) 

clf2.fit(X_train, y_train)

predict_y = clf2.predict(X_test)

getResults(predict_y, y_test)

Precision: 1.0 
Recall: 1.0 
Accuracy: 1.0 
Fscore: 1.0


### Recovery

In [118]:
X_train, X_test, y_train, y_test = train_test_split(X3, y3, test_size=0.33, random_state=random.randint(0, 50))

clf3 = make_pipeline(StandardScaler(), XGBClassifier(n_estimators=100)) 

clf3.fit(X_train, y_train)

predict_y = clf3.predict(X_test)

getResults(predict_y, y_test)

Precision: 1.0 
Recall: 0.75 
Accuracy: 0.8636363636363636 
Fscore: 0.8571428571428571


# Anomaly Detection Models

In [119]:
from sklearn.ensemble import IsolationForest
from sklearn.svm import OneClassSVM

In [120]:
scaler = StandardScaler()

## One Class SVM

In [121]:
# X 

In [122]:
# y

### Catch

In [123]:
X_train = X[y == 0]

clf1 = OneClassSVM(
    gamma='auto', 
    kernel='rbf', #rbf is best when many dimensions
    nu=0.5).fit(X_train)

y_pred_train = clf1.predict(X)

y_pred_train

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

### Pull

In [124]:
#X2 needs to be scaled
X_train2 = X2[y2 == 0]

X_train2_scaled = scaler.fit_transform(X_train2)
X2_scaled = scaler.transform(X2)

clf2 = OneClassSVM(
    gamma='auto', 
    kernel='rbf', #rbf is best when many dimensions
    nu=0.5).fit(X_train2_scaled)

y_pred_train2 = clf2.predict(X2_scaled)

y_pred_train2

array([-1, -1,  1, -1,  1,  1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1,
       -1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,  1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

### Recovery

In [125]:
X_train3 = X3[y3 == 0]

clf3 = OneClassSVM(
    gamma='auto', 
    kernel='rbf', #rbf is best when many dimensions
    nu=0.5).fit(X_train3)

y_pred_train3 = clf3.predict(X3)

y_pred_train3

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

## Isolation Forest

### Catch

In [126]:
X_train = X[y == 0]

clf1 = IsolationForest(
    n_estimators=100,
    max_samples='auto',
    contamination=.4, #percent of outliers
    random_state=random.randint(0,50)).fit(X_train)

y_pred_train = clf1.predict(X)

y_pred_train

array([-1, -1,  1, -1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,  1, -1,  1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

### Pull

In [127]:
#X2 needs to be scaled
X_train2 = X2[y2 == 0]

X_train2_scaled = scaler.fit_transform(X_train2)
X2_scaled = scaler.transform(X2)

clf2 = IsolationForest(
    n_estimators=100,
    max_samples='auto',
    contamination=.4, #percent of outliers
    random_state=random.randint(0,50)).fit(X_train2_scaled)

y_pred_train2 = clf2.predict(X2_scaled)

y_pred_train2

array([-1, -1,  1, -1,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

### Recovery

In [128]:
X_train3 = X3[y3 == 0]

clf3 = IsolationForest(
    n_estimators=100,
    max_samples='auto',
    contamination=.4, #percent of outliers
    random_state=random.randint(0,50)).fit(X_train3)

y_pred_train = clf3.predict(X3)

y_pred_train

array([-1, -1, -1, -1,  1, -1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])