In [168]:
# You should be able to run all cells of this notebook sequentially without errors
# Provided that the assets files are in the correct place

In [ ]:
from matplotlib import dates as mdate
from matplotlib import pyplot as plt
import matplotlib.animation as animation
import pandas as pd
from time import sleep
from IPython.display import clear_output
import numpy as np

In [169]:
OptimalPhoneAccel = pd.read_csv("../../Sensor data/Anthony Optimal/Phone 2024-12-11_21-58-56/AccelerometerUncalibrated.csv")
OptimalPhoneGyro = pd.read_csv("../../Sensor data/Anthony Optimal/Phone 2024-12-11_21-58-56/GyroscopeUncalibrated.csv")
OptimalPhoneMag = pd.read_csv("../../Sensor data/Anthony Optimal/Phone 2024-12-11_21-58-56/MagnetometerUncalibrated.csv")

In [170]:
OptimalWatchAccel = pd.read_csv("../../Sensor data/Anthony Optimal/Watch 2024-12-11_21-58-56/AccelerometerUncalibrated.csv")
OptimalWatchGyro = pd.read_csv("../../Sensor data/Anthony Optimal/Watch 2024-12-11_21-58-56/GyroscopeUncalibrated.csv")
OptimalWatchMag = pd.read_csv("../../Sensor data/Anthony Optimal/Watch 2024-12-11_21-58-56/MagnetometerUncalibrated.csv")

In [171]:
InoptimalPhoneAccel = pd.read_csv("../../Sensor data/Anthony Inoptimal/Phone 2024-12-11_22-03-28/AccelerometerUncalibrated.csv")
InoptimalPhoneGyro = pd.read_csv("../../Sensor data/Anthony Inoptimal/Phone 2024-12-11_22-03-28/GyroscopeUncalibrated.csv")
InoptimalPhoneMag = pd.read_csv("../../Sensor data/Anthony Inoptimal/Phone 2024-12-11_22-03-28/MagnetometerUncalibrated.csv")

In [172]:
InoptimalWatchAccel = pd.read_csv("../../Sensor data/Anthony Inoptimal/Watch 2024-12-11_22-03-28/AccelerometerUncalibrated.csv")
InoptimalWatchGyro = pd.read_csv("../../Sensor data/Anthony Inoptimal/Watch 2024-12-11_22-03-28/GyroscopeUncalibrated.csv")
InoptimalWatchMag = pd.read_csv("../../Sensor data/Anthony Inoptimal/Watch 2024-12-11_22-03-28/MagnetometerUncalibrated.csv")

In [173]:
PhoneTime = OptimalPhoneAccel["time"];
WatchTime = OptimalWatchAccel["time"];

PhoneAccelX = OptimalPhoneAccel["x"];
PhoneAccelY = OptimalPhoneAccel["y"];
PhoneAccelZ = OptimalPhoneAccel["z"];

PhoneGyroX = OptimalPhoneGyro["x"];
PhoneGyroY = OptimalPhoneGyro["y"];
PhoneGyroZ = OptimalPhoneGyro["z"];

PhoneMagX = OptimalPhoneMag["x"];
PhoneMagY = OptimalPhoneMag["y"];
PhoneMagZ = OptimalPhoneMag["z"];

WatchAccelX = OptimalWatchAccel["x"];
WatchAccelY = OptimalWatchAccel["y"];
WatchAccelZ = OptimalWatchAccel["z"];

WatchGyroX = OptimalWatchGyro["x"];
WatchGyroY = OptimalWatchGyro["y"];
WatchGyroZ = OptimalWatchGyro["z"];

WatchMagX = OptimalWatchMag["x"];
WatchMagY = OptimalWatchMag["y"];
WatchMagZ = OptimalWatchMag["z"];

In [174]:
OptimalDict = {
    "PhoneTime": PhoneTime,
    "WatchTime": WatchTime,
    
    "PhoneAccelX": PhoneAccelX,
    "PhoneAccelY": PhoneAccelY,
    "PhoneAccelZ": PhoneAccelZ,
    
    "PhoneGyroX": PhoneGyroX,
    "PhoneGyroY": PhoneGyroY,
    "PhoneGyroZ": PhoneGyroZ,
    
    "PhoneMagX": PhoneMagX,
    "PhoneMagY": PhoneMagY,
    "PhoneMagZ": PhoneMagZ,
    
    "WatchAccelX": WatchAccelX,
    "WatchAccelY": WatchAccelY,
    "WatchAccelZ": WatchAccelZ,
    
    "WatchGyroX": WatchGyroX,
    "WatchGyroY": WatchGyroY,
    "WatchGyroZ": WatchGyroZ,
    
    "WatchMagX": WatchMagX,
    "WatchMagY": WatchMagY,
    "WatchMagZ": WatchMagZ
    
}


In [176]:
#  // one thing to take into account
# // is the phone aligned with the watch
# // if not, we need to align it

currentwatchtime = OptimalDict["WatchTime"][0]
currentphonetime = OptimalDict["PhoneTime"][0]
pushmetric = 0

if (currentwatchtime < currentphonetime):
#     // watch started early, lets push it
    pushmetric = "watch";
else:
#     // phone started early, lets push it
    pushmetric = "phone";


# // keep pushing it until the opposite is true
windex = 0;
pindex = 0;
while (True):
#     // alert("pushing", currentwatchtime-currentphonetime,pushmetric);
#     // console.log("pushing", currentwatchtime,currentphonetime, currentwatchtime-currentphonetime,pushmetric);
    currentwatchtime = OptimalDict["WatchTime"][windex];
    currentphonetime = OptimalDict["PhoneTime"][pindex];

    if (currentwatchtime > currentphonetime and pushmetric == "watch"):
        break
    

    if (currentwatchtime < currentphonetime and pushmetric == "phone"):
        break
    

    if (pushmetric == "watch"):
        windex += 1;
    else:
        pindex += 1;
    


print("use indices ", windex, pindex, "with times", OptimalDict["WatchTime"][windex], OptimalDict["PhoneTime"][pindex]);
# // notify of the delta. raise error if its too much

print("delta is", (OptimalDict["WatchTime"][windex]-OptimalDict["PhoneTime"][pindex])/(1000000000));

if (windex != 0):
#     // slice index
#     // slice all of the watch attributes of sample dict, keep windex and beyond
    OptimalDict["WatchTime"] = OptimalDict["WatchTime"][windex:]
    OptimalDict["WatchAccelX"] = OptimalDict["WatchAccelX"][windex:]
    OptimalDict["WatchAccelY"] = OptimalDict["WatchAccelY"][windex:]
    OptimalDict["WatchAccelZ"] = OptimalDict["WatchAccelZ"][windex:]
    OptimalDict["WatchGyroX"] = OptimalDict["WatchGyroX"][windex:]
    OptimalDict["WatchGyroY"] = OptimalDict["WatchGyroY"][windex:]
    OptimalDict["WatchGyroZ"] = OptimalDict["WatchGyroZ"][windex:]
    OptimalDict["WatchMagX"] = OptimalDict["WatchMagX"][windex:]
    OptimalDict["WatchMagY"] = OptimalDict["WatchMagY"][windex:]
    OptimalDict["WatchMagZ"] = OptimalDict["WatchMagZ"][windex:]
else:
#     // the same thing but for phone attributes
    OptimalDict["PhoneTime"] = OptimalDict["PhoneTime"][pindex:]
    OptimalDict["PhoneAccelX"] = OptimalDict["PhoneAccelX"][pindex:]
    OptimalDict["PhoneAccelY"] = OptimalDict["PhoneAccelY"][pindex:]
    OptimalDict["PhoneAccelZ"] = OptimalDict["PhoneAccelZ"][pindex:]
    OptimalDict["PhoneGyroX"] = OptimalDict["PhoneGyroX"][pindex:]
    OptimalDict["PhoneGyroY"] = OptimalDict["PhoneGyroY"][pindex:]
    OptimalDict["PhoneGyroZ"] = OptimalDict["PhoneGyroZ"][pindex:]
    OptimalDict["PhoneMagX"] = OptimalDict["PhoneMagX"][pindex:]
    OptimalDict["PhoneMagY"] = OptimalDict["PhoneMagY"][pindex:]
    OptimalDict["PhoneMagZ"] = OptimalDict["PhoneMagZ"][pindex:]
    

    



use indices  7 0 with times 1733954337011733000 1733954337009982000
delta is 0.001751


In [178]:
# // lengths of strokes
streaks = [];


strokearr = [];

currentstroke = {
    "PhoneAccelX": [],
    "PhoneAccelY": [],
    "PhoneAccelZ": [],
    "PhoneGyroX": [],
    "PhoneGyroY": [],
    "PhoneGyroZ": [],
    "PhoneMagX": [],
    "PhoneMagY": [],
    "PhoneMagZ": [],

    "WatchAccelX": [],
    "WatchAccelY": [],
    "WatchAccelZ": [],
    "WatchGyroX": [],
    "WatchGyroY": [],
    "WatchGyroZ": [],
    "WatchMagX": [],
    "WatchMagY": [],
    "WatchMagZ": [],

    "PhoneTime": [],
    "WatchTime": []
}


watchstart = windex
phonestart = pindex



#  and phonestart < len(OptimalDict["PhoneGyroX"]) and phonestart < len(OptimalDict["PhoneMagX"]) 
#        and watchstart < len(OptimalDict["WatchAccelX"]) and watchstart < len(OptimalDict["WatchGyroX"]) and watchstart < len(OptimalDict["WatchMagX"])
i = 0;
last = 0;
while (phonestart < len(OptimalDict["PhoneAccelX"]) and phonestart < len(OptimalDict["PhoneGyroX"]) and phonestart < len(OptimalDict["PhoneMagX"]) 
       and watchstart < len(OptimalDict["WatchAccelX"]) and watchstart < len(OptimalDict["WatchGyroX"]) and watchstart < len(OptimalDict["WatchMagX"])
):
    subj = OptimalDict["PhoneGyroX"][phonestart];
    
#     print(i)

#     // i think this is way more surefire now

    if (i < len(OptimalDict["PhoneGyroX"])-4 and subj > OptimalDict["PhoneGyroX"][phonestart+1] and OptimalDict["PhoneGyroX"][phonestart+1] > OptimalDict["PhoneGyroX"][phonestart+2] and OptimalDict["PhoneGyroX"][phonestart+3] > OptimalDict["PhoneGyroX"][phonestart+4] and i-last > 100 and subj > 0.8):

        strokearr.append(currentstroke);

        currentstroke = {
            "PhoneAccelX": [],
            "PhoneAccelY": [],
            "PhoneAccelZ": [],
            "PhoneGyroX": [],
            "PhoneGyroY": [],
            "PhoneGyroZ": [],
            "PhoneMagX": [],
            "PhoneMagY": [],
            "PhoneMagZ": [],

            "WatchAccelX": [],
            "WatchAccelY": [],
            "WatchAccelZ": [],
            "WatchGyroX": [],
            "WatchGyroY": [],
            "WatchGyroZ": [],
            "WatchMagX": [],
            "WatchMagY": [],
            "WatchMagZ": [],

            "PhoneTime": [],
            "WatchTime": []
        }

        streaks.append(i-last) #; // will usually be around the threshold

        last = i;
        
#     print("currenti",i)
#     print("currentdiff",i-last)
        
#     currentstroke["PhoneTime"].append(0)
#     print(currentstroke["PhoneTime"])
#     print(OptimalDict["PhoneTime"][i])
    
#     currentstroke["PhoneTime"].append(OptimalDict["PhoneTime"][i]);
#     currentstroke["WatchTime"].append(OptimalDict["WatchTime"][i]);

    if (i-last < 155):

        currentstroke["PhoneAccelX"].append(OptimalDict["PhoneAccelX"][phonestart]);
        currentstroke["PhoneAccelY"].append(OptimalDict["PhoneAccelY"][phonestart]);
        currentstroke["PhoneAccelZ"].append(OptimalDict["PhoneAccelZ"][phonestart]);
        currentstroke["PhoneGyroX"].append(OptimalDict["PhoneGyroX"][phonestart]);
        currentstroke["PhoneGyroY"].append(OptimalDict["PhoneGyroY"][phonestart]);
        currentstroke["PhoneGyroZ"].append(OptimalDict["PhoneGyroZ"][phonestart]);
        currentstroke["PhoneMagX"].append(OptimalDict["PhoneMagX"][phonestart]);
        currentstroke["PhoneMagY"].append(OptimalDict["PhoneMagY"][phonestart]);
        currentstroke["PhoneMagZ"].append(OptimalDict["PhoneMagZ"][phonestart]);

        currentstroke["WatchAccelX"].append(OptimalDict["WatchAccelX"][watchstart]);
        currentstroke["WatchAccelY"].append(OptimalDict["WatchAccelY"][watchstart]);
        currentstroke["WatchAccelZ"].append(OptimalDict["WatchAccelZ"][watchstart]);
        currentstroke["WatchGyroX"].append(OptimalDict["WatchGyroX"][watchstart]);
        currentstroke["WatchGyroY"].append(OptimalDict["WatchGyroY"][watchstart]);
        currentstroke["WatchGyroZ"].append(OptimalDict["WatchGyroZ"][watchstart]);
        currentstroke["WatchMagX"].append(OptimalDict["WatchMagX"][watchstart]);
        currentstroke["WatchMagY"].append(OptimalDict["WatchMagY"][watchstart]);
        currentstroke["WatchMagZ"].append(OptimalDict["WatchMagZ"][watchstart]);

    i += 1;
    watchstart += 1
    phonestart += 1

    
print(streaks);

# // noew find out the differences
differences = [];
i = 1;
while (i < len(streaks)):
    differences.append(streaks[i]-streaks[i-1]);
    i += 1


print(differences);


starts = [];
lns = [];

currentstart = 0;
currentlen = 0;
i = 0;
while (i < len(differences)):
#     print("current i",i);
    if (differences[i] < 70 and differences[i] > -70):
#         // within regulation, len goes up
        currentlen += 1;
    else:
#         // out of regulation, cut it off
        lns.append(currentlen);
        starts.append(currentstart);

        currentlen = 0;
        currentstart = i+1;
        
    # check if thats the end
    if (i == len(differences)-1):
        lns.append(currentlen);
        starts.append(currentstart);

        currentlen = 0;
        currentstart = i+1;


    i += 1;


print(starts);
print(lns);

# if the length is above 2, use it



strokearray = [];
# // only take the ones that were approved by the automation

# // send any set of strokes larger than 2 for evaluation

i = 0;
while (i < len(starts)):
    if (lns[i] > 2):
#         // actually do the thing

        j = starts[i];
        while (j < starts[i]+lns[i]):
            if (len(strokearr[j]["PhoneAccelX"]) >= 155):
                strokearray.append(strokearr[j]);
            
            j += 1;
        
    
#     // else skip over it
    i += 1;


[770, 596, 753, 171, 167, 159, 167, 176, 216, 164, 205, 313, 175, 156, 190, 165, 174, 183, 186, 183, 178, 278, 173, 197, 190, 193, 197, 197, 199, 211, 192, 197, 194, 206, 188, 205, 190, 189, 202, 199]
[-174, 157, -582, -4, -8, 8, 9, 40, -52, 41, 108, -138, -19, 34, -25, 9, 9, 3, -3, -5, 100, -105, 24, -7, 3, 4, 0, 2, 12, -19, 5, -3, 12, -18, 17, -15, -1, 13, -3]
[0, 1, 2, 3, 11, 12, 21, 22]
[0, 0, 0, 7, 0, 8, 0, 17]


In [182]:


n = 0

completearr = []
resultarr = []

for n in range(len(strokearray)):

    arr1 = [
        strokearray[n]["PhoneAccelX"],
        strokearray[n]["PhoneAccelY"],
        strokearray[n]["PhoneAccelZ"],
        strokearray[n]["PhoneGyroX"],
        strokearray[n]["PhoneGyroY"],
        strokearray[n]["PhoneGyroZ"],
        strokearray[n]["PhoneMagX"],
        strokearray[n]["PhoneMagY"],
        strokearray[n]["PhoneMagZ"],
        strokearray[n]["WatchAccelX"],
        strokearray[n]["WatchAccelY"],
        strokearray[n]["WatchAccelZ"],
        strokearray[n]["WatchGyroX"],
        strokearray[n]["WatchGyroY"],
        strokearray[n]["WatchGyroZ"],
        strokearray[n]["WatchMagX"],
        strokearray[n]["WatchMagY"],
        strokearray[n]["WatchMagZ"],
    ];

    finarr = [];
    for i in arr1:
        for j in i:
            finarr.append(j)
            
    resultarr.append(0)

    completearr.append(finarr)

In [184]:
# now look at inoptimal

In [185]:
PhoneTime = InoptimalPhoneAccel["time"];
WatchTime = InoptimalWatchAccel["time"];

PhoneAccelX = InoptimalPhoneAccel["x"];
PhoneAccelY = InoptimalPhoneAccel["y"];
PhoneAccelZ = InoptimalPhoneAccel["z"];

PhoneGyroX = InoptimalPhoneGyro["x"];
PhoneGyroY = InoptimalPhoneGyro["y"];
PhoneGyroZ = OptimalPhoneGyro["z"];

PhoneMagX = InoptimalPhoneMag["x"];
PhoneMagY = InoptimalPhoneMag["y"];
PhoneMagZ = InoptimalPhoneMag["z"];

WatchAccelX = InoptimalWatchAccel["x"];
WatchAccelY = InoptimalWatchAccel["y"];
WatchAccelZ = InoptimalWatchAccel["z"];

WatchGyroX = InoptimalWatchGyro["x"];
WatchGyroY = InoptimalWatchGyro["y"];
WatchGyroZ = InoptimalWatchGyro["z"];

WatchMagX = InoptimalWatchMag["x"];
WatchMagY = InoptimalWatchMag["y"];
WatchMagZ = InoptimalWatchMag["z"];

In [186]:
InoptimalDict = {
    "PhoneTime": PhoneTime,
    "WatchTime": WatchTime,
    
    "PhoneAccelX": PhoneAccelX,
    "PhoneAccelY": PhoneAccelY,
    "PhoneAccelZ": PhoneAccelZ,
    
    "PhoneGyroX": PhoneGyroX,
    "PhoneGyroY": PhoneGyroY,
    "PhoneGyroZ": PhoneGyroZ,
    
    "PhoneMagX": PhoneMagX,
    "PhoneMagY": PhoneMagY,
    "PhoneMagZ": PhoneMagZ,
    
    "WatchAccelX": WatchAccelX,
    "WatchAccelY": WatchAccelY,
    "WatchAccelZ": WatchAccelZ,
    
    "WatchGyroX": WatchGyroX,
    "WatchGyroY": WatchGyroY,
    "WatchGyroZ": WatchGyroZ,
    
    "WatchMagX": WatchMagX,
    "WatchMagY": WatchMagY,
    "WatchMagZ": WatchMagZ
}


In [187]:
#  // one thing to take into account
# // is the phone aligned with the watch
# // if not, we need to align it

currentwatchtime = InoptimalDict["WatchTime"][0]
currentphonetime = InoptimalDict["PhoneTime"][0]
pushmetric = 0

if (currentwatchtime < currentphonetime):
#     // watch started early, lets push it
    pushmetric = "watch";
else:
#     // phone started early, lets push it
    pushmetric = "phone";


# // keep pushing it until the opposite is true
windex = 0;
pindex = 0;
while (True):
#     // alert("pushing", currentwatchtime-currentphonetime,pushmetric);
#     // console.log("pushing", currentwatchtime,currentphonetime, currentwatchtime-currentphonetime,pushmetric);
    currentwatchtime = InoptimalDict["WatchTime"][windex];
    currentphonetime = InoptimalDict["PhoneTime"][pindex];

    if (currentwatchtime > currentphonetime and pushmetric == "watch"):
        break
    

    if (currentwatchtime < currentphonetime and pushmetric == "phone"):
        break
    

    if (pushmetric == "watch"):
        windex += 1;
    else:
        pindex += 1;
    


print("use indices ", windex, pindex, "with times", InoptimalDict["WatchTime"][windex], InoptimalDict["PhoneTime"][pindex]);
# // notify of the delta. raise error if its too much

print("delta is", (InoptimalDict["WatchTime"][windex]-InoptimalDict["PhoneTime"][pindex])/(1000000000));

if (windex != 0):
#     // slice index
#     // slice all of the watch attributes of sample dict, keep windex and beyond
    InoptimalDict["WatchTime"] = InoptimalDict["WatchTime"][windex:]
    InoptimalDict["WatchAccelX"] = InoptimalDict["WatchAccelX"][windex:]
    InoptimalDict["WatchAccelY"] = InoptimalDict["WatchAccelY"][windex:]
    InoptimalDict["WatchAccelZ"] = InoptimalDict["WatchAccelZ"][windex:]
    InoptimalDict["WatchGyroX"] = InoptimalDict["WatchGyroX"][windex:]
    InoptimalDict["WatchGyroY"] = InoptimalDict["WatchGyroY"][windex:]
    InoptimalDict["WatchGyroZ"] = InoptimalDict["WatchGyroZ"][windex:]
    InoptimalDict["WatchMagX"] = InoptimalDict["WatchMagX"][windex:]
    InoptimalDict["WatchMagY"] = InoptimalDict["WatchMagY"][windex:]
    InoptimalDict["WatchMagZ"] = InoptimalDict["WatchMagZ"][windex:]
else:
#     // the same thing but for phone attributes
    InoptimalDict["PhoneTime"] = InoptimalDict["PhoneTime"][pindex:]
    InoptimalDict["PhoneAccelX"] = InoptimalDict["PhoneAccelX"][pindex:]
    InoptimalDict["PhoneAccelY"] = InoptimalDict["PhoneAccelY"][pindex:]
    InoptimalDict["PhoneAccelZ"] = InoptimalDict["PhoneAccelZ"][pindex:]
    InoptimalDict["PhoneGyroX"] = InoptimalDict["PhoneGyroX"][pindex:]
    InoptimalDict["PhoneGyroY"] = InoptimalDict["PhoneGyroY"][pindex:]
    InoptimalDict["PhoneGyroZ"] = InoptimalDict["PhoneGyroZ"][pindex:]
    InoptimalDict["PhoneMagX"] = InoptimalDict["PhoneMagX"][pindex:]
    InoptimalDict["PhoneMagY"] = InoptimalDict["PhoneMagY"][pindex:]
    InoptimalDict["PhoneMagZ"] = InoptimalDict["PhoneMagZ"][pindex:]
    

    



use indices  15 0 with times 1733954609029301200 1733954609026177000
delta is 0.0031242


In [188]:
# // lengths of strokes
streaks = [];


strokearr = [];

currentstroke = {
    "PhoneAccelX": [],
    "PhoneAccelY": [],
    "PhoneAccelZ": [],
    "PhoneGyroX": [],
    "PhoneGyroY": [],
    "PhoneGyroZ": [],
    "PhoneMagX": [],
    "PhoneMagY": [],
    "PhoneMagZ": [],

    "WatchAccelX": [],
    "WatchAccelY": [],
    "WatchAccelZ": [],
    "WatchGyroX": [],
    "WatchGyroY": [],
    "WatchGyroZ": [],
    "WatchMagX": [],
    "WatchMagY": [],
    "WatchMagZ": [],

    "PhoneTime": [],
    "WatchTime": []
}


watchstart = windex
phonestart = pindex


i = 0;
last = 0;
while (phonestart < len(InoptimalDict["PhoneAccelX"]) and phonestart < len(InoptimalDict["PhoneGyroZ"]) and phonestart < len(InoptimalDict["PhoneMagX"]) 
       and watchstart < len(InoptimalDict["WatchAccelX"]) and watchstart < len(InoptimalDict["WatchGyroX"]) and watchstart < len(InoptimalDict["WatchMagX"])):
    
    
    subj = InoptimalDict["PhoneGyroX"][phonestart];

#     // i think this is way more surefire now

    if (i < len(InoptimalDict["PhoneGyroX"])-4 and subj > InoptimalDict["PhoneGyroX"][phonestart+1] and InoptimalDict["PhoneGyroX"][phonestart+1] > InoptimalDict["PhoneGyroX"][phonestart+2] and InoptimalDict["PhoneGyroX"][phonestart+3] > InoptimalDict["PhoneGyroX"][phonestart+4] and phonestart-last > 100 and subj > 0.8):

        strokearr.append(currentstroke);

        currentstroke = {
            "PhoneAccelX": [],
            "PhoneAccelY": [],
            "PhoneAccelZ": [],
            "PhoneGyroX": [],
            "PhoneGyroY": [],
            "PhoneGyroZ": [],
            "PhoneMagX": [],
            "PhoneMagY": [],
            "PhoneMagZ": [],

            "WatchAccelX": [],
            "WatchAccelY": [],
            "WatchAccelZ": [],
            "WatchGyroX": [],
            "WatchGyroY": [],
            "WatchGyroZ": [],
            "WatchMagX": [],
            "WatchMagY": [],
            "WatchMagZ": [],

            "PhoneTime": [],
            "WatchTime": []
        }

        streaks.append(i-last) #; // will usually be around the threshold

        last = i;
        
        
        
#     currentstroke["PhoneTime"].append(0)
#     print(currentstroke["PhoneTime"])
#     print(OptimalDict["PhoneTime"][i])
    
#     currentstroke["PhoneTime"].append(OptimalDict["PhoneTime"][i]);
#     currentstroke["WatchTime"].append(OptimalDict["WatchTime"][i]);

    if (i-last < 155):

        currentstroke["PhoneAccelX"].append(InoptimalDict["PhoneAccelX"][phonestart]);
        currentstroke["PhoneAccelY"].append(InoptimalDict["PhoneAccelY"][phonestart]);
        currentstroke["PhoneAccelZ"].append(InoptimalDict["PhoneAccelZ"][phonestart]);
        currentstroke["PhoneGyroX"].append(InoptimalDict["PhoneGyroX"][phonestart]);
        currentstroke["PhoneGyroY"].append(InoptimalDict["PhoneGyroY"][phonestart]);
        currentstroke["PhoneGyroZ"].append(InoptimalDict["PhoneGyroZ"][phonestart]);
        currentstroke["PhoneMagX"].append(InoptimalDict["PhoneMagX"][phonestart]);
        currentstroke["PhoneMagY"].append(InoptimalDict["PhoneMagY"][phonestart]);
        currentstroke["PhoneMagZ"].append(InoptimalDict["PhoneMagZ"][phonestart]);

        currentstroke["WatchAccelX"].append(InoptimalDict["WatchAccelX"][watchstart]);
        currentstroke["WatchAccelY"].append(InoptimalDict["WatchAccelY"][watchstart]);
        currentstroke["WatchAccelZ"].append(InoptimalDict["WatchAccelZ"][watchstart]);
        currentstroke["WatchGyroX"].append(InoptimalDict["WatchGyroX"][watchstart]);
        currentstroke["WatchGyroY"].append(InoptimalDict["WatchGyroY"][watchstart]);
        currentstroke["WatchGyroZ"].append(InoptimalDict["WatchGyroZ"][watchstart]);
        currentstroke["WatchMagX"].append(InoptimalDict["WatchMagX"][watchstart]);
        currentstroke["WatchMagY"].append(InoptimalDict["WatchMagY"][watchstart]);
        currentstroke["WatchMagZ"].append(InoptimalDict["WatchMagZ"][watchstart]);

    i += 1;
    watchstart += 1
    phonestart += 1

    
print(streaks);

# // noew find out the differences
differences = [];
i = 1;
while (i < len(streaks)):
    differences.append(streaks[i]-streaks[i-1]);
    i += 1


print(differences);


starts = [];
lns = [];

currentstart = 0;
currentlen = 0;
i = 0;
while (i < len(differences)):
    if (differences[i] < 70 and differences[i] > -70):
#         // within regulation, len goes up
        currentlen += 1;
    else:
#         // out of regulation, cut it off
        lns.append(currentlen);
        starts.append(currentstart);

        currentlen = 0;
        currentstart = i+1;
        
    # check if thats the end
    if (i == len(differences)-1):
        lns.append(currentlen);
        starts.append(currentstart);

        currentlen = 0;
        currentstart = i+1;
    

    i += 1;


print(starts);
print(lns);

# if the length is above 2, use it



strokearray = [];
# // only take the ones that were approved by the automation

# // send any set of strokes larger than 2 for evaluation

i = 0;
while (i < len(starts)):
    if (lns[i] > 2):
#         // actually do the thing

        j = starts[i];
        while (j < starts[i]+lns[i]):
            if (len(strokearr[j]["PhoneAccelX"]) >= 155):
                strokearray.append(strokearr[j]);
            
            j += 1;
        
    
#     // else skip over it
    i += 1;


[411, 297, 172, 257, 301, 454, 222, 217, 204, 233, 195, 223, 211, 230, 205, 201, 264, 219, 271, 260, 228, 246, 228, 226, 220, 244, 222, 222, 221, 221, 224, 243, 263, 204, 270, 272, 237, 200, 231, 398, 230]
[-114, -125, 85, 44, 153, -232, -5, -13, 29, -38, 28, -12, 19, -25, -4, 63, -45, 52, -11, -32, 18, -18, -2, -6, 24, -22, 0, -1, 0, 3, 19, 20, -59, 66, 2, -35, -37, 31, 167, -168]
[0, 1, 2, 3, 5, 6, 39, 40]
[0, 0, 0, 1, 0, 32, 0, 0]


In [189]:


n = 0

for n in range(len(strokearray)):

    arr1 = [
        strokearray[n]["PhoneAccelX"],
        strokearray[n]["PhoneAccelY"],
        strokearray[n]["PhoneAccelZ"],
        strokearray[n]["PhoneGyroX"],
        strokearray[n]["PhoneGyroY"],
        strokearray[n]["PhoneGyroZ"],
        strokearray[n]["PhoneMagX"],
        strokearray[n]["PhoneMagY"],
        strokearray[n]["PhoneMagZ"],
        strokearray[n]["WatchAccelX"],
        strokearray[n]["WatchAccelY"],
        strokearray[n]["WatchAccelZ"],
        strokearray[n]["WatchGyroX"],
        strokearray[n]["WatchGyroY"],
        strokearray[n]["WatchGyroZ"],
        strokearray[n]["WatchMagX"],
        strokearray[n]["WatchMagY"],
        strokearray[n]["WatchMagZ"],
    ];

    finarr = [];
    for i in arr1:
        for j in i:
            finarr.append(j)
            
    resultarr.append(1)

    completearr.append(finarr)

In [190]:
completearr = np.array(completearr);
completearr

array([[ -0.8372345 ,  -0.84689331,  -0.85375977, ...,  -5.38763428,
         -5.15589905,  -5.34065247],
       [ -0.79545593,  -0.82171631,  -0.83644104, ...,  -6.44056702,
         -6.91210938,  -6.89080811],
       [ -0.79145813,  -0.78466797,  -0.78929138, ...,  -5.11448669,
         -5.07495117,  -4.86985779],
       ...,
       [ -0.50297546,  -0.51609802,  -0.52996826, ..., -57.40357971,
        -57.30299377, -57.35473633],
       [ -0.66429138,  -0.68058777,  -0.68562317, ..., -59.75030518,
        -59.54342651, -59.58293152],
       [ -0.54934692,  -0.57766724,  -0.60017395, ..., -55.25338745,
        -55.05781555, -55.37236023]])

In [191]:
resultarr = np.array(resultarr);
resultarr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
# model changes below this

In [192]:
X = completearr
y = resultarr

In [199]:
import random
from sklearn.model_selection import train_test_split

import numpy as np

from sklearn.pipeline import make_pipeline

from sklearn.preprocessing import StandardScaler

from sklearn.svm import SVC

from sklearn.linear_model import LogisticRegression

from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import cross_val_score

import pickle




In [194]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=random.randint(0, 50))

clf1 = make_pipeline(StandardScaler(), SVC(gamma='auto'))

clf1.fit(X_train, y_train)

predict_y = clf1.predict(X_test)
predict_y

array([0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1])

In [195]:
y_test

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1])

In [196]:
with open('Model_New_Train_Method.pkl','wb') as f:
    pickle.dump(clf1,f)

In [201]:
RF_model = make_pipeline(StandardScaler(), LogisticRegression(penalty='l2')) #penalty prevents overfitting

RF_model.fit(X_train, y_train)

predict_y = RF_model.predict(X_test)

predict_y

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1])

In [202]:
y_test

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1])