In [2]:
from matplotlib import dates as mdate
from matplotlib import pyplot as plt
import matplotlib.animation as animation
import pandas as pd
from time import sleep
from IPython.display import clear_output
import numpy as np
from scipy.stats import skew

In [3]:
# df = pd.read_csv("../Paddling_Data/Jan_24/Anthony Optimal (1)/LeftWatch.csv")

In [4]:
optimalFileBase = [
    {"PhoneAccel": "../Paddling_Data/Jan_24/Anthony Optimal (1)/AccelerometerUncalibrated.csv",
     "PhoneGyro": "../Paddling_Data/Jan_24/Anthony Optimal (1)/GyroscopeUncalibrated.csv",
     "PhoneMag": "../Paddling_Data/Jan_24/Anthony Optimal (1)/MagnetometerUncalibrated.csv",
     "LeftWatch": "../Paddling_Data/Jan_24//Anthony Optimal (1)/LeftWatch.csv",
     "RightWatch": "../Paddling_Data/Jan_24//Anthony Optimal (1)/RightWatch.csv"
    },
    {"PhoneAccel": "../Paddling_Data/Jan_24//Alex Optimal (1)/AccelerometerUncalibrated.csv",
     "PhoneGyro": "../Paddling_Data/Jan_24//Alex Optimal (1)/GyroscopeUncalibrated.csv",
     "PhoneMag": "../Paddling_Data/Jan_24//Alex Optimal (1)/MagnetometerUncalibrated.csv",
     "LeftWatch": "../Paddling_Data/Jan_24//Alex Optimal (1)/LeftWatch.csv",
     "RightWatch": "../Paddling_Data/Jan_24//Alex Optimal (1)/RightWatch.csv"
    },
    {"PhoneAccel": "../Paddling_Data/Jan_24//Alex Optimal (2)/AccelerometerUncalibrated.csv",
     "PhoneGyro": "../Paddling_Data/Jan_24//Alex Optimal (2)/GyroscopeUncalibrated.csv",
     "PhoneMag": "../Paddling_Data/Jan_24//Alex Optimal (2)/MagnetometerUncalibrated.csv",
     "LeftWatch": "../Paddling_Data/Jan_24//Alex Optimal (2)/LeftWatch.csv",
     "RightWatch": "../Paddling_Data/Jan_24//Alex Optimal (2)/RightWatch.csv"
    },
    {"PhoneAccel": "../Paddling_Data/Jan_24//Tony Optimal (1)/AccelerometerUncalibrated.csv",
     "PhoneGyro": "../Paddling_Data/Jan_24//Tony Optimal (1)/GyroscopeUncalibrated.csv",
     "PhoneMag": "../Paddling_Data/Jan_24//Tony Optimal (1)/MagnetometerUncalibrated.csv",
     "LeftWatch": "../Paddling_Data/Jan_24//Tony Optimal (1)/LeftWatch.csv",
     "RightWatch": "../Paddling_Data/Jan_24//Tony Optimal (1)/RightWatch.csv"
    },
    {"PhoneAccel": "../Paddling_Data/Jan_24//Tony Optimal (2)/AccelerometerUncalibrated.csv",
     "PhoneGyro": "../Paddling_Data/Jan_24//Tony Optimal (2)/GyroscopeUncalibrated.csv",
     "PhoneMag": "../Paddling_Data/Jan_24//Tony Optimal (2)/MagnetometerUncalibrated.csv",
     "LeftWatch": "../Paddling_Data/Jan_24//Tony Optimal (2)/LeftWatch.csv",
     "RightWatch": "../Paddling_Data/Jan_24//Tony Optimal (2)/RightWatch.csv"
    },
    {"PhoneAccel": "../Paddling_Data/Jan_24//Anthony Inoptimal (1)/AccelerometerUncalibrated.csv",
     "PhoneGyro": "../Paddling_Data/Jan_24//Anthony Inoptimal (1)/GyroscopeUncalibrated.csv",
     "PhoneMag": "../Paddling_Data/Jan_24//Anthony Inoptimal (1)/MagnetometerUncalibrated.csv",
     "LeftWatch": "../Paddling_Data/Jan_24//Anthony Inoptimal (1)/LeftWatch.csv",
     "RightWatch": "../Paddling_Data/Jan_24//Anthony Inoptimal (1)/RightWatch.csv"
    },
    {"PhoneAccel": "../Paddling_Data/Jan_24//Shubham Optimal (1)/AccelerometerUncalibrated.csv",
     "PhoneGyro": "../Paddling_Data/Jan_24//Shubham Optimal (1)/GyroscopeUncalibrated.csv",
     "PhoneMag": "../Paddling_Data/Jan_24//Shubham Optimal (1)/MagnetometerUncalibrated.csv",
     "LeftWatch": "../Paddling_Data/Jan_24//Shubham Optimal (1)/LeftWatch.csv",
     "RightWatch": "../Paddling_Data/Jan_24//Shubham Optimal (1)/RightWatch.csv"
    },
];

In [5]:
def createFullDict(fileBaseDict):
    
    PhoneAccel = pd.read_csv(fileBaseDict["PhoneAccel"])
    PhoneGyro = pd.read_csv(fileBaseDict["PhoneGyro"])
    PhoneMag = pd.read_csv(fileBaseDict["PhoneMag"])
    LeftWatch = pd.read_csv(fileBaseDict["LeftWatch"])
    RightWatch = pd.read_csv(fileBaseDict["RightWatch"])
        
    
    Dict = {
        "PhoneTime": PhoneAccel["time"],
        "LeftWatchTime": LeftWatch[" TimeSince1970(ms)"],
        "RightWatchTime": RightWatch[" TimeSince1970(ms)"],

        "PhoneAccelX": PhoneAccel["x"],
        "PhoneAccelY": PhoneAccel["y"],
        "PhoneAccelZ": PhoneAccel["z"],

        "PhoneGyroX": PhoneGyro["x"],
        "PhoneGyroY": PhoneGyro["y"],
        "PhoneGyroZ": PhoneGyro["z"],

        "PhoneMagX": PhoneMag["x"],
        "PhoneMagY": PhoneMag["y"],
        "PhoneMagZ": PhoneMag["z"],

        "LeftWatchRoll": LeftWatch[" DMRoll"],
        "LeftWatchPitch": LeftWatch[" DMPitch"],
        "LeftWatchYaw": LeftWatch[" DMYaw"],

        "LeftWatchRotX": LeftWatch[" DMRotX"],
        "LeftWatchRotY": LeftWatch[" DMRotY"],
        "LeftWatchRotZ": LeftWatch[" DMRotZ"],

        "LeftWatchGravX": LeftWatch[" DMGrvX"],
        "LeftWatchGravY": LeftWatch[" DMGrvY"],
        "LeftWatchGravZ": LeftWatch[" DMGrvZ"],
        
        "LeftWatchDMUAccelX": LeftWatch[" DMUAccelX"],
        "LeftWatchDMUAccelY": LeftWatch[" DMUAccelY"],
        "LeftWatchDMUAccelZ": LeftWatch[" DMUAccelZ"],
        
        "LeftWatchQuatW": LeftWatch[" DMQuatW"],
        "LeftWatchQuatX": LeftWatch[" DMQuatX"],
        "LeftWatchQuatY": LeftWatch[" DMQuatY"],
        "LeftWatchQuatZ": LeftWatch[" DMQuatZ"],
    
        "LeftWatchAccelX": LeftWatch["AccelroX"],
        "LeftWatchAccelY": LeftWatch[" AceelroY"],
        "LeftWatchAccelZ": LeftWatch[" AceelroZ"],
        
        "RightWatchRoll": RightWatch[" DMRoll"],
        "RightWatchPitch": RightWatch[" DMPitch"],
        "RightWatchYaw": RightWatch[" DMYaw"],

        "RightWatchRotX": RightWatch[" DMRotX"],
        "RightWatchRotY": RightWatch[" DMRotY"],
        "RightWatchRotZ": RightWatch[" DMRotZ"],

        "RightWatchGravX": RightWatch[" DMGrvX"],
        "RightWatchGravY": RightWatch[" DMGrvY"],
        "RightWatchGravZ": RightWatch[" DMGrvZ"],
        
        "RightWatchDMUAccelX": RightWatch[" DMUAccelX"],
        "RightWatchDMUAccelY": RightWatch[" DMUAccelY"],
        "RightWatchDMUAccelZ": RightWatch[" DMUAccelZ"],
        
        "RightWatchQuatW": RightWatch[" DMQuatW"],
        "RightWatchQuatX": RightWatch[" DMQuatX"],
        "RightWatchQuatY": RightWatch[" DMQuatY"],
        "RightWatchQuatZ": RightWatch[" DMQuatZ"],
    
        "RightWatchAccelX": RightWatch["AccelroX"],
        "RightWatchAccelY": RightWatch[" AceelroY"],
        "RightWatchAccelZ": RightWatch[" AceelroZ"]
    }
    
    return Dict

In [6]:
def clipArray(Dict, attribute, clipLen):
    Dict[attribute] = Dict[attribute][clipLen:]

In [7]:
def alignTimings(currentDict):
    currentPhoneTime = currentDict["PhoneTime"][0]
    currentLeftWatchTime = currentDict["LeftWatchTime"][0]*1000000
    currentRightWatchTime = currentDict["RightWatchTime"][0]*1000000
    
    holdMetric = None
    
    if (currentPhoneTime >= currentLeftWatchTime and currentPhoneTime >= currentRightWatchTime):
        holdMetric = "currentPhoneTime"
    elif (currentLeftWatchTime >= currentPhoneTime and currentLeftWatchTime >= currentRightWatchTime):
        holdMetric = "currentLeftWatchTime"
    else:
        holdMetric = "currentRightWatchTime"
    
    
    pindex = 0;
    wlindex = 0;
    wrindex = 0;
    while (True):
        currentPhoneTime = currentDict["PhoneTime"][pindex];
        currentLeftWatchTime = currentDict["LeftWatchTime"][wlindex]*1000000;
        currentRightWatchTime = currentDict["RightWatchTime"][wrindex]*1000000;
        
        
#         print(currentPhoneTime,currentLeftWatchTime,currentRightWatchTime)

        if (holdMetric == "currentPhoneTime"):
            if (currentLeftWatchTime < currentPhoneTime and currentRightWatchTime < currentPhoneTime):
                wlindex += 1;
                wrindex += 1;
            elif (currentLeftWatchTime < currentPhoneTime):
                wlindex += 1;
            elif (currentRightWatchTime < currentPhoneTime):
                wrindex += 1;
            else:
                break
    
        elif (holdMetric == "currentLeftWatchTime"):
            if (currentPhoneTime < currentLeftWatchTime and currentRightWatchTime < currentLeftWatchTime):
                pindex += 1;
                wrindex += 1;
            elif (currentPhoneTime < currentLeftWatchTime):
                pindex += 1;
            elif (currentRightWatchTime < currentLeftWatchTime):
                wrindex += 1;
            else:
                break

        else:
            if (currentPhoneTime < currentRightWatchTime and currentLeftWatchTime < currentRightWatchTime):
                pindex += 1;
                wlindex += 1;
            elif (currentPhoneTime < currentRightWatchTime):
                pindex += 1;
            elif (currentLeftWatchTime < currentRightWatchTime):
                wlindex += 1;
            else:
                break

    print("delta is", (currentDict["PhoneTime"][pindex]-currentDict["LeftWatchTime"][wlindex]*1000000)/(1000000000));
    print("delta is", (currentDict["PhoneTime"][pindex]-currentDict["RightWatchTime"][wrindex]*1000000)/(1000000000));


    PhoneAttributes = ["PhoneTime", "PhoneAccelX", "PhoneAccelY", "PhoneAccelZ", "PhoneGyroX",
                       "PhoneGyroY", "PhoneGyroZ", "PhoneMagX", "PhoneMagY", "PhoneMagZ"]
                       
    LeftWatchAttributes = ["LeftWatchTime", "LeftWatchRoll", "LeftWatchPitch", "LeftWatchYaw","LeftWatchRotX", 
                           "LeftWatchRotY", "LeftWatchRotZ", "LeftWatchGravX", "LeftWatchGravY", "LeftWatchGravZ", 
                           "LeftWatchDMUAccelX", "LeftWatchDMUAccelY", "LeftWatchDMUAccelZ", "LeftWatchQuatW",
                           "LeftWatchQuatX", "LeftWatchQuatY", "LeftWatchQuatZ", "LeftWatchAccelX",
                           "LeftWatchAccelY", "LeftWatchAccelZ"]
    RightWatchAttributes = ["RightWatchTime", "RightWatchRoll", "RightWatchPitch", "RightWatchYaw", "RightWatchRotX", 
                            "RightWatchRotY", "RightWatchRotZ", "RightWatchGravX", "RightWatchGravY",
                            "RightWatchGravZ", "RightWatchDMUAccelX", "RightWatchDMUAccelY", "RightWatchDMUAccelZ",
                            "RightWatchQuatW", "RightWatchQuatX", "RightWatchQuatY", "RightWatchQuatZ",
                            "RightWatchAccelX", "RightWatchAccelY", "RightWatchAccelZ"]

    for i in PhoneAttributes:
        clipArray(currentDict, i, pindex)
    
    for i in LeftWatchAttributes:
        clipArray(currentDict, i, wlindex)
    
    for i in RightWatchAttributes:
        clipArray(currentDict, i, wrindex)
        
    return [pindex, wlindex, wrindex]

In [8]:
def addReading(newDict, oldDict, pindex, wlindex, wrindex):
    attributes = ["PhoneTime", "PhoneAccelX", "PhoneAccelY", "PhoneAccelZ", "PhoneGyroX",
                   "PhoneGyroY", "PhoneGyroZ", "PhoneMagX", "PhoneMagY", "PhoneMagZ", "LeftWatchTime", 
                   "LeftWatchRoll", "LeftWatchPitch", "LeftWatchYaw","LeftWatchRotX", 
                   "LeftWatchRotY", "LeftWatchRotZ", "LeftWatchGravX", "LeftWatchGravY", "LeftWatchGravZ", 
                   "LeftWatchDMUAccelX", "LeftWatchDMUAccelY", "LeftWatchDMUAccelZ", "LeftWatchQuatW",
                   "LeftWatchQuatX", "LeftWatchQuatY", "LeftWatchQuatZ", "LeftWatchAccelX",
                   "LeftWatchAccelY", "LeftWatchAccelZ", "RightWatchTime", "RightWatchRoll", 
                   "RightWatchPitch", "RightWatchYaw", "RightWatchRotX", 
                   "RightWatchRotY", "RightWatchRotZ", "RightWatchGravX", "RightWatchGravY",
                   "RightWatchGravZ", "RightWatchDMUAccelX", "RightWatchDMUAccelY", "RightWatchDMUAccelZ",
                   "RightWatchQuatW", "RightWatchQuatX", "RightWatchQuatY", "RightWatchQuatZ",
                   "RightWatchAccelX", "RightWatchAccelY", "RightWatchAccelZ"]
        
    for i in attributes:
        index = ""
        if ("Phone" in i):
            index = pindex
        elif ("LeftWatch" in i):
            index = wlindex
        else:
            index = wrindex
            
#         print(index, wrindex)
        
        
        if (i in newDict):
            newDict[i].append(oldDict[i][index])
        else:
#             print("attribute",i)
#             print(oldDict[i])
            newDict[i] = [oldDict[i][index]]
    

In [9]:
def continuouslydownward(arr, startIndex, wantlength):
    checked = startIndex
    
    anomalies = 0
    while (checked < startIndex+wantlength):
        
        if (len(arr) <= startIndex+wantlength):
#             print("left cuz of end", checked-startIndex)
            return False
        if (arr[checked] < arr[checked+1]):
#             print("left cuz of higher", checked-startIndex)
            anomalies += 1
        
        checked += 1
    
    return anomalies <= 3
    
    

In [10]:
def splitIntoStrokes(currentDict, pindex, wlindex, wrindex):

    streaks = [];

    strokearr = [];

    currentstroke = {}

    pstart = pindex
    wlstart = wlindex
    wrstart = wrindex

    i = 0;
    last = 0;
    while (pstart < len(currentDict["PhoneAccelX"]) and wlstart < len(currentDict["LeftWatchRoll"])
          and wrstart < len(currentDict["RightWatchRoll"])):
        subj = currentDict["LeftWatchQuatX"][wlstart];
        
#         print("inside out", wlstart, subj)


        # cut it off as a stroke
        if (continuouslydownward(currentDict["LeftWatchQuatX"], wlstart, 40) and i-last > 150):
            
            
#             print("inside")


            strokearr.append(currentstroke);

            currentstroke = {}

            streaks.append(i-last) #; // will usually be around the threshold

            last = i;

        # Limit will be taken care of by the stroke splitter
        if (True or i-last < 190):
            
            addReading(currentstroke, currentDict, pstart, wlstart, wrstart)

        i += 1;
        pstart += 1
        wlstart += 1
        wrstart += 1

    print(streaks);

    # // noew find out the differences
    differences = [];
    i = 1;
    while (i < len(streaks)):
        differences.append(streaks[i]-streaks[i-1]);
        i += 1


    print(differences);


    starts = [];
    lns = [];

    currentstart = 0;
    currentlen = 0;
    i = 0;
    while (i < len(differences)):
    #     print("current i",i);
        if (differences[i] < 70 and differences[i] > -70):
    #         // within regulation, len goes up
            currentlen += 1;
        else:
    #         // out of regulation, cut it off
            lns.append(currentlen);
            starts.append(currentstart);

            currentlen = 0;
            currentstart = i+1;

        # check if thats the end
        if (i == len(differences)-1):
            lns.append(currentlen);
            starts.append(currentstart);

            currentlen = 0;
            currentstart = i+1;


        i += 1;


    print(starts);
    print(lns);

    # if the length is above 2, use it



    strokearray = [];
    # // only take the ones that were approved by the automation

    # // send any set of strokes larger than 2 for evaluation

    i = 0;
    while (i < len(starts)):
        if (lns[i] > 2):
    #         // actually do the thing

            j = starts[i];
            while (j < starts[i]+lns[i]):
#                 print(len(strokearr[j]["PhoneAccelX"]))
                if (len(strokearr[j]["PhoneAccelX"]) >= 190):
                    strokearray.append(strokearr[j]);

                j += 1;


    #     // else skip over it
        i += 1;
        
    return strokearray;


In [11]:
def splitIntoParts(currentDict):
    
    # currentDict is a dict with attributes of arrays

    streaks = [];

    strokearr = [];
    
    splitalready = False;
    secondsplitalready = False;

    currentstroke = {}

    i = 0;
    while (i < len(currentDict["PhoneAccelX"]) and i < len(currentDict["LeftWatchRoll"])
          and i < len(currentDict["RightWatchRoll"])):
        
#         print("in loop, at index", i)
        
        subj = currentDict["LeftWatchQuatW"][i];

        # i want to see if its increasing consistently
        if ((not splitalready) and 
            i < len(currentDict["LeftWatchQuatW"])-17 and subj < currentDict["LeftWatchQuatW"][i+1] 
            and currentDict["LeftWatchQuatW"][i+1] < currentDict["LeftWatchQuatW"][i+2] 
            and currentDict["LeftWatchQuatW"][i+2] < currentDict["LeftWatchQuatW"][i+3] 
            and currentDict["LeftWatchQuatW"][i+3] < currentDict["LeftWatchQuatW"][i+4] 
            and currentDict["LeftWatchQuatW"][i+4] < currentDict["LeftWatchQuatW"][i+5] 
            and currentDict["LeftWatchQuatW"][i+5] < currentDict["LeftWatchQuatW"][i+6] 
            and currentDict["LeftWatchQuatW"][i+6] < currentDict["LeftWatchQuatW"][i+7] 
            and currentDict["LeftWatchQuatW"][i+7] < currentDict["LeftWatchQuatW"][i+8] 
            and currentDict["LeftWatchQuatW"][i+8] < currentDict["LeftWatchQuatW"][i+9] 
            and currentDict["LeftWatchQuatW"][i+9] < currentDict["LeftWatchQuatW"][i+10] 
            and currentDict["LeftWatchQuatW"][i+10] < currentDict["LeftWatchQuatW"][i+11] 
            and currentDict["LeftWatchQuatW"][i+11] < currentDict["LeftWatchQuatW"][i+12] 
            and currentDict["LeftWatchQuatW"][i+12] < currentDict["LeftWatchQuatW"][i+13] 
            and currentDict["LeftWatchQuatW"][i+13] < currentDict["LeftWatchQuatW"][i+14] 
            and currentDict["LeftWatchQuatW"][i+14] < currentDict["LeftWatchQuatW"][i+15] 
            and currentDict["LeftWatchQuatW"][i+15] < currentDict["LeftWatchQuatW"][i+16] 
            and currentDict["LeftWatchQuatW"][i+16] < currentDict["LeftWatchQuatW"][i+17]):
            
#             print("first split out, at index", i)

            strokearr.append(currentstroke)
            
            splitalready = True
            
            currentstroke = {}
            
    
         # now i want to see if its decreasing consistently
        if ((splitalready) and (not secondsplitalready) and
            i < len(currentDict["LeftWatchQuatW"])-10 and subj > currentDict["LeftWatchQuatW"][i+1] 
            and currentDict["LeftWatchQuatW"][i+1] > currentDict["LeftWatchQuatW"][i+2] 
            and currentDict["LeftWatchQuatW"][i+2] > currentDict["LeftWatchQuatW"][i+3] 
            and currentDict["LeftWatchQuatW"][i+3] > currentDict["LeftWatchQuatW"][i+4] 
            and currentDict["LeftWatchQuatW"][i+4] > currentDict["LeftWatchQuatW"][i+5] 
            and currentDict["LeftWatchQuatW"][i+5] > currentDict["LeftWatchQuatW"][i+6] 
            and currentDict["LeftWatchQuatW"][i+6] > currentDict["LeftWatchQuatW"][i+7] 
            and currentDict["LeftWatchQuatW"][i+7] > currentDict["LeftWatchQuatW"][i+8] 
            and currentDict["LeftWatchQuatW"][i+8] > currentDict["LeftWatchQuatW"][i+9]):
            
            
#             print("second split out, at index", i)


            strokearr.append(currentstroke)
            
            secondsplitalready = True
            
            currentstroke = {}
    
    
        addReading(currentstroke, currentDict, i, i, i)

        i += 1;

    strokearr.append(currentstroke);

#     print("last split out, at index", i)
#

    return strokearr;

In [12]:
def getSummaryStats(arr):
    #dont flatten, summarize into mean, skewness, stdev, min, max, range, 75th percentile, 25th percentile


    retarr = [np.mean(arr), skew(arr), np.std(arr), np.min(arr), np.max(arr), np.max(arr)-np.min(arr), np.percentile(arr, 25), np.percentile(arr, 75)]
    
    return retarr

def convertToSummary(dct):
    attributes = ["PhoneTime", "PhoneAccelX", "PhoneAccelY", "PhoneAccelZ", "PhoneGyroX",
                   "PhoneGyroY", "PhoneGyroZ", "PhoneMagX", "PhoneMagY", "PhoneMagZ", "LeftWatchTime", 
                   "LeftWatchRoll", "LeftWatchPitch", "LeftWatchYaw","LeftWatchRotX", 
                   "LeftWatchRotY", "LeftWatchRotZ", "LeftWatchGravX", "LeftWatchGravY", "LeftWatchGravZ", 
                   "LeftWatchDMUAccelX", "LeftWatchDMUAccelY", "LeftWatchDMUAccelZ", "LeftWatchQuatW",
                   "LeftWatchQuatX", "LeftWatchQuatY", "LeftWatchQuatZ", "LeftWatchAccelX",
                   "LeftWatchAccelY", "LeftWatchAccelZ", "RightWatchTime", "RightWatchRoll", 
                   "RightWatchPitch", "RightWatchYaw", "RightWatchRotX", 
                   "RightWatchRotY", "RightWatchRotZ", "RightWatchGravX", "RightWatchGravY",
                   "RightWatchGravZ", "RightWatchDMUAccelX", "RightWatchDMUAccelY", "RightWatchDMUAccelZ",
                   "RightWatchQuatW", "RightWatchQuatX", "RightWatchQuatY", "RightWatchQuatZ",
                   "RightWatchAccelX", "RightWatchAccelY", "RightWatchAccelZ"]
    
    
    endarr = []
    
    for feature in attributes:
        endarr.extend(getSummaryStats(dct[feature]))
        
    return endarr
    

In [13]:
def getResults(predict_y, y_test):
    true_pos = 0
    true_neg = 0
    false_pos = 0
    false_neg = 0

    i = 0
    while (i < len(predict_y)):
        pred = predict_y[i]
        real = y_test[i]

        if (pred == real and pred == 1):
            true_pos += 1
        elif (pred == real and pred == 0):
            true_neg += 1
        elif (pred != real and real == 0):
            false_pos += 1
        else:
            false_neg += 1

        i += 1


    precision = (true_pos)/(true_pos+false_pos)
    recall = (true_pos)/(true_pos+false_neg)
    accuracy = (true_pos+true_neg)/(true_pos+true_neg+false_pos+false_neg)
    fscore = 2*(precision*recall)/(precision+recall)
    
    print("Precision:",precision,"\nRecall:",recall,"\nAccuracy:",accuracy,"\nFscore:",fscore)

In [14]:
def filesToTrain(num, label):
    global catchcompletearr
    global catchresultarr

    global pullcompletearr
    global pullresultarr

    global recoverycompletearr
    global recoveryresultarr
    
    dct = createFullDict(optimalFileBase[num])
    ret = alignTimings(dct)
#     print(ret)
    strokearray = splitIntoStrokes(dct, ret[0],ret[1],ret[2])
    
    i = 0
    while (i < len(strokearray)):
        starr = splitIntoParts(strokearray[i]);
        
        if (len(starr) != 3 or starr[0] == {} or starr[1] == {} or starr[2] == {}):
            # splitting didnt work, discard
            i += 1
            continue
        else:
            catchcompletearr.append(convertToSummary(starr[0]))
            catchresultarr.append(label)
            
            pullcompletearr.append(convertToSummary(starr[1]))
            pullresultarr.append(label)
            
            recoverycompletearr.append(convertToSummary(starr[2]))
            recoveryresultarr.append(label)

        i += 1

Training below

In [15]:
catchcompletearr = []
catchresultarr = []

pullcompletearr = []
pullresultarr = []

recoverycompletearr = []
recoveryresultarr = []

In [16]:
filesToTrain(0, 0)

delta is 0.004619
delta is 0.000619
[378, 151, 247, 151, 151, 178, 172, 190, 188, 190, 195, 189, 212, 187, 193, 227, 169, 194, 210, 198, 213, 203, 206, 212, 204, 213, 208, 225, 208, 222, 212, 230, 230, 220, 216, 217, 225, 231, 216, 209, 207, 216, 214, 151, 664]
[-227, 96, -96, 0, 27, -6, 18, -2, 2, 5, -6, 23, -25, 6, 34, -58, 25, 16, -12, 15, -10, 3, 6, -8, 9, -5, 17, -17, 14, -10, 18, 0, -10, -4, 1, 8, 6, -15, -7, -2, 9, -2, -63, 513]
[0, 1, 2, 3, 44]
[0, 0, 0, 40, 0]


In [17]:
filesToTrain(1, 0)

delta is 0.0030754
delta is 0.0020754
[384, 291, 367, 254, 151, 151, 203, 280, 200, 191, 244, 215, 457, 160, 267, 154, 271, 196, 207, 232, 243, 222, 843, 228, 194, 273, 151, 185, 213, 390, 175, 216, 195, 262, 165, 151, 206, 167, 172, 234, 204, 181, 234, 198, 318, 153]
[-93, 76, -113, -103, 0, 52, 77, -80, -9, 53, -29, 242, -297, 107, -113, 117, -75, 11, 25, 11, -21, 621, -615, -34, 79, -122, 34, 28, 177, -215, 41, -21, 67, -97, -14, 55, -39, 5, 62, -30, -23, 53, -36, 120, -165]
[0, 1, 2, 3, 4, 7, 8, 12, 13, 14, 15, 16, 17, 22, 23, 25, 26, 29, 30, 34, 44, 45]
[0, 0, 0, 0, 2, 0, 3, 0, 0, 0, 0, 0, 4, 0, 1, 0, 2, 0, 3, 9, 0, 0]


In [18]:
filesToTrain(2, 0)

delta is -0.0027882
delta is -0.0057882
[151, 154, 180, 151, 261, 456, 176, 453, 285, 186, 198, 244, 195, 160, 229, 235, 359, 228, 185, 151, 151, 157, 172, 250, 459, 300, 259, 213, 194, 151, 321, 151, 276, 187, 349, 275, 328, 243, 218, 249, 155, 304, 179, 237, 162, 176, 280, 186, 239, 151, 295, 505]
[3, 26, -29, 110, 195, -280, 277, -168, -99, 12, 46, -49, -35, 69, 6, 124, -131, -43, -34, 0, 6, 15, 78, 209, -159, -41, -46, -19, -43, 170, -170, 125, -89, 162, -74, 53, -85, -25, 31, -94, 149, -125, 58, -75, 14, 104, -94, 53, -88, 144, 210]
[0, 4, 5, 6, 7, 8, 9, 16, 17, 23, 24, 25, 30, 31, 32, 33, 34, 35, 37, 40, 41, 42, 44, 46, 47, 49, 50, 51]
[3, 0, 0, 0, 0, 0, 6, 0, 5, 0, 0, 4, 0, 0, 0, 0, 0, 1, 2, 0, 0, 1, 1, 0, 1, 0, 0, 0]


In [19]:
# filesToTrain(3, 0)
# Failed

In [20]:
filesToTrain(4, 1)

delta is 0.0004387
delta is -0.0045613
[176, 558, 417, 316, 151, 151, 151, 162, 211, 168, 184, 151, 162, 169, 174, 178, 155, 180, 233, 151, 192, 197, 188, 180, 198, 177, 190, 169, 341, 199, 202, 172, 162, 307, 219, 169, 186, 329, 517, 151, 207, 443, 932, 162, 667, 182, 171, 339, 187, 234, 616, 515, 221, 151, 296, 298, 197, 508, 311, 229, 201, 168, 170, 180, 158, 179, 164, 170, 166, 164, 192, 157, 171, 188, 234, 214, 204, 181, 251, 156, 229, 197, 220, 219, 228, 306, 151, 151]
[382, -141, -101, -165, 0, 0, 11, 49, -43, 16, -33, 11, 7, 5, 4, -23, 25, 53, -82, 41, 5, -9, -8, 18, -21, 13, -21, 172, -142, 3, -30, -10, 145, -88, -50, 17, 143, 188, -366, 56, 236, 489, -770, 505, -485, -11, 168, -152, 47, 382, -101, -294, -70, 145, 2, -101, 311, -197, -82, -28, -33, 2, 10, -22, 21, -15, 6, -4, -2, 28, -35, 14, 17, 46, -20, -10, -23, 70, -95, 73, -32, 23, -1, 9, 78, -155, 0]
[0, 1, 2, 3, 4, 19, 28, 29, 33, 34, 37, 38, 39, 41, 42, 43, 44, 45, 47, 48, 50, 51, 52, 53, 54, 56, 57, 58, 59, 78, 79, 80

In [21]:
filesToTrain(5, 1)

delta is -0.0075467
delta is -0.0085467
[151, 318, 479, 176, 176, 178, 192, 187, 187, 188, 211, 236, 259, 151, 178, 193, 190, 192, 195, 186, 205, 202, 198, 194, 202, 198, 211, 208, 215, 209, 196, 220, 220, 223, 220, 231, 151, 188, 580]
[167, 161, -303, 0, 2, 14, -5, 0, 1, 23, 25, 23, -108, 27, 15, -3, 2, 3, -9, 19, -3, -4, -4, 8, -4, 13, -3, 7, -6, -13, 24, 0, 3, -3, 11, -80, 37, 392]
[0, 1, 2, 3, 13, 36, 38]
[0, 0, 0, 9, 22, 1, 0]


In [22]:
X = np.array(catchcompletearr)
y = np.array(catchresultarr)

In [23]:
X

array([[ 1.73774944e+18,  3.60507967e-06,  9.29481312e+07, ...,
         7.34313965e-01, -6.10542297e-01, -2.20668793e-01],
       [ 1.73774944e+18,  4.01499878e-06,  1.13298473e+08, ...,
         1.04241943e+00, -6.90299988e-01, -2.81784058e-01],
       [ 1.73774944e+18,  6.51203180e-06,  9.87631425e+07, ...,
         9.00222778e-01, -5.94234467e-01, -1.36581421e-01],
       ...,
       [ 1.73774977e+18, -3.24646505e-06,  2.35386941e+08, ...,
         9.68460083e-01, -6.55563354e-01, -1.27639771e-01],
       [ 1.73774977e+18,  1.01621607e-06,  2.09228192e+08, ...,
         7.90176392e-01, -4.08485413e-01, -1.56967163e-01],
       [ 1.73774978e+18,  8.04025401e-06,  1.48189040e+08, ...,
         8.17703247e-01, -5.36857605e-01, -1.44218445e-01]],
      shape=(66, 400))

In [24]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
len(X)

66

In [26]:
len(y)

66

In [27]:
import random
from sklearn.model_selection import train_test_split

import numpy as np

from sklearn.pipeline import make_pipeline

from sklearn.preprocessing import StandardScaler

from sklearn.svm import SVC

from sklearn.linear_model import LogisticRegression

from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import cross_val_score

import pickle

# Catch

In [28]:
X = np.array(catchcompletearr)
y = np.array(catchresultarr)

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=random.randint(0, 50))

clf1 = make_pipeline(StandardScaler(), SVC(gamma='auto'))

clf1.fit(X_train, y_train)

predict_y = clf1.predict(X_test)
predict_y

array([1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1])

In [30]:
y_test

array([1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1])

In [31]:
getResults(predict_y, y_test)

Precision: 1.0 
Recall: 1.0 
Accuracy: 1.0 
Fscore: 1.0


# Pull

In [32]:
X = np.array(pullcompletearr)
y = np.array(pullresultarr)

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=random.randint(0, 50))

clf1 = make_pipeline(StandardScaler(), SVC(gamma='auto'))

clf1.fit(X_train, y_train)

predict_y = clf1.predict(X_test)
predict_y

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0])

In [34]:
getResults(predict_y, y_test)

Precision: 1.0 
Recall: 0.9 
Accuracy: 0.9545454545454546 
Fscore: 0.9473684210526316


In [35]:
X = np.array(recoverycompletearr)
y = np.array(recoveryresultarr)

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=random.randint(0, 50))

clf1 = make_pipeline(StandardScaler(), SVC(gamma='auto'))

clf1.fit(X_train, y_train)

predict_y = clf1.predict(X_test)
predict_y

array([0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1])

# Recovery

In [43]:
getResults(predict_y, y_test)


Precision: 1.0 
Recall: 1.0 
Accuracy: 1.0 
Fscore: 1.0
